baseURL = 'https://cuny2x.github.io/'
languageCode = 'en-us'
title = 'Welcome to CUNY 2X'
theme = "hugo-theme-learn"

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "red"


disableSearch = true
disableNextPrev = true

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Application Now Open"
url = "apply"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Computer Science"
url = "https://www.laguardia.edu/majors/computer-science"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Computer Technology, AAS"
url = "https://www.laguardia.edu/majors/computer-technology"
weight = 30

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Cybersecurity, AAS"
url = "https://www.laguardia.edu/majors/cybersecurity/"
weight = 40

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Programming and Software Development, AAS"
url = "https://www.laguardia.edu/majors/programming-and-software-development/"
weight = 50