baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Welcome to CUNY 2X'
theme = "hugo-theme-learn"

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "red"


disableSearch = true
disableNextPrev = true